name: Run commands in nix env
description: |
  Pulls the nix cache and runs commands within the nix environment.


inputs:
  commands:
    required: false
    type: string

  working-directory:
    required: true
    type: string
    default: '/'

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
    - uses: ./.github/actions/nix-cache

    - shell: nix develop ./ -c bash -e {0}
      run: |
        cd ${{ inputs.working-directory }}
        ${{inputs.commands}}