-- UP
BEGIN;

--! To Do: status should be an enum type, 
--! but for simplicity, will use text for now


--! User table - working stations
create table users (
    user_id int generated by default as identity primary key,
    user_name text unique not null --! login name
);

--! Role table
create table roles (
    role_id int generated by default as identity primary key,
    role_name text unique not null, --! role name
    role_description text --! role description
);

--! User-Role association table
create table user_roles (
    user_id int references users(user_id) on delete cascade,
    role_id int references roles(role_id) on delete cascade,
    primary key (user_id, role_id)
);


create table permissions (
    permission_id int generated by default as identity primary key,
    permission_name text unique not null, --! permission name
    permission_description text --! permission description
);

--! Role-Permission association table
create table role_permissions (
    role_id int references roles(role_id) on delete cascade,
    permission_id int references permissions(permission_id) on delete cascade,
    primary key (role_id, permission_id) --! composite primary key
);

create table operations (
    operation_id int generated by default as identity primary key,
    operation_name text unique not null, --! operation name
    operation_timestamp timestamp with time zone default now(), --! operation timestamp
    operation_description text, --! operation description
    operation_status text --! operation status
);

create table user_operations (
    user_id int references users(user_id) on delete cascade,
    operation_id int references operations(operation_id) on delete cascade,

    primary key (user_id, operation_id) --! composite primary key
);

create table maps (
    map_id int generated by default as identity primary key,
    map_timestamp timestamp with time zone default now(), --! map creation timestamp
    map_type text not null, --! map type (e.g., "world", "city", "building")
    map_geo_data jsonb not null, --! geo data in GeoJSON format
    map_description text, --! map description
    map_status text, --! map status

    operation_id int not null references operations(operation_id) on delete cascade --! reference to associated operation; assumption: a map belongs to one operation
);

create table tactical_signs (
    sign_id int generated by default as identity primary key,
    sign_name text unique not null, --! tactical sign name
    sign_description text, --! tactical sign description
    sign_image bytea --! tactical sign image (optional)
);

create table map_tactical_signs (
    map_id int references maps(map_id) on delete cascade,
    sign_id int references tactical_signs(sign_id) on delete cascade,

    primary key (map_id, sign_id) --! composite primary key
);

create table points_of_interest (
    poi_id int generated by default as identity primary key,
    poi_name text not null, --! point of interest name
    poi_description text,
    poi_location jsonb not null,
    map_id int not null references maps(map_id) on delete cascade --! reference to associated map; assumption: a POI belongs to one map
);

create table grids (
    grid_id int generated by default as identity primary key,
    grid_metadata jsonb not null, --! grid metadata (e.g., grid size, origin, resolution)
    grid_data_reference text not null, --! reference to grid data (e.g., file path, URL)
    map_id int not null references maps(map_id) on delete cascade --! reference to associated map
);

--! Indexes for performance optimization
create index idx_user_roles_role_id on user_roles(role_id);
create index idx_role_permissions_permission_id on role_permissions(permission_id);
create index idx_user_operations_user_id on user_operations(user_id);
create index idx_user_operations_operation_id on user_operations(operation_id);
create index idx_maps_operation_id on maps(operation_id);
create index idx_map_tactical_signs_sign_id on map_tactical_signs(sign_id);
create index idx_points_of_interest_map_id on points_of_interest(map_id);
create index idx_grids_map_id on grids(map_id);

COMMIT;