name: CI
description: |
  Includes the whole CI pipeline.
  First creates a new nix cache, if no matching one exists.
  Then runs different checks 

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}@${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  build-cache-nix-ci:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-cache

  backend-checks:
    needs: build-cache-nix-ci
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context:
          [
            # [cargo command, requires database?]
            ["fmt -- --check", false],
            ["clippy -- -D warnings --allow clippy::needless_return", false],
            ["test", true],
          ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-in-nix-env
        with:
          commands: |
            ${{ case(matrix.context[1] == true, 'db-start', '') }} # doesnt work yet (at least with act)
            # db-start
            cargo ${{ matrix.context[0] }}
          working-directory: backend/

  frontend-checks:
    needs: build-cache-nix-ci
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context:
          [
            ["lint"],
            ["typecheck"],
            ["build"]
          ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-in-nix-env
        with:
          commands: |
            npm ci
            npm run ${{ matrix.context[0] }}
          working-directory: frontend/
